#!/usr/bin/env python3
import subprocess

WORKSPACE_DIR = "vendor/openfst"

def run_bazel_query(target):
    query = f'kind("source file", deps({target}))'

    result = subprocess.run(
        ["bazel", "query", query, "--output=label"],
        cwd=WORKSPACE_DIR,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=True
    )
    return result.stdout.strip().split('\n')

def bazel_label_to_path(label):
    if not label or not label.endswith(".cc"):
        return None

    if label.startswith("@com_google_absl//"):
        path = label.replace("@com_google_absl//", "vendor/abseil-cpp/")
        return path.replace(":", "/")

    elif label.startswith("//"):
        path = label.replace("//", "vendor/openfst/")
        return path.replace(":", "/")

    return None

def main():
    print("Querying Bazel for OpenFST core dependencies...")

    labels = set()
    labels.update(run_bazel_query("//openfst/lib:lib"))
    labels.update(run_bazel_query("//openfst/compat:compat"))

    source_paths = []
    for label in labels:
        path = bazel_label_to_path(label)
        if path:
            if "test" not in path and "benchmark" not in path:
                source_paths.append(path)

    source_paths.sort()

    out_file = "src/generated_srcs.rs"
    with open(out_file, "w") as f:
        f.write("// @generated by scripts/generate_srcs.py\n")
        f.write("// DO NOT EDIT MANUALLY\n\n")
        f.write("pub const OPENFST_SRCS: &[&str] = &[\n")
        for path in source_paths:
            f.write(f'    "{path}",\n')
        f.write("];\n")

    print(f"Successfully generated {out_file} with {len(source_paths)} source files.")

if __name__ == "__main__":
    main()